// react_src/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import TodoApp from './components/TodoApp';
import './App.css';

class App extends Component {
  render() {
    return (
      <div class="columns is-multiline is-centered">
        <div className="App-header column is-12 has-text-centered">
          <img src={logo} className="App-logo" alt="logo" />
        </div>

        <div class="column is-12 has-text-centered">
          <h1 class="title"> Todo list de exemplo em React </h1>
        </div>

        <div class="column is-half">
          <TodoApp />
        </div>
      </div>
    );
  }
}

export default App

// vue_src/src/App.vue
<template>
  <div id="app">
    <div class="columns is-multiline is-centered">
      <div class="column is-12 has-text-centered">
        <img alt="Vue logo" src="./assets/logo.png" class="is-centered">
      </div>

      <div class="column is-12 has-text-centered">
        <h1 class="title"> Todo list de exemplo em Vuejs </h1>
      </div>

      <div class="column is-half">
        <TodoList />
      </div>
    </div>
  </div>
</template>

<script>
import TodoList from './components/TodoList/index.vue'

export default {
  name: 'app',
  components: {
    TodoList
  }
}
</script>
