// angular-src/src/app/todo-item/todo-item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { TodoItem } from '../todo-item';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent implements OnInit {

  @Input() item: TodoItem;

  @Input() index: number;

  @Output() change = new EventEmitter<TodoItem>();

  @Output() delete = new EventEmitter<TodoItem>();

  showInput = false;

  constructor() { }

  ngOnInit() {
  }

  editItem () {
    this.showInput = !this.showInput
  }

  deleteElement () {
    this.delete.emit(this.item)
  }

  handleBlur () {
    this.showInput = !this.showInput

    this.change.emit(this.item)
  }

}

<div class="columns">
  <div class="column is-11">
    <li *ngIf="!showInput" (click)="editItem()"> {{ item.value }} </li>
    <input
      class="input is-primary"
      type="text"
      [(ngModel)]="item.value"
      name="value"
      *ngIf="showInput"
      (blur)="handleBlur()">
  </div>
  
  <div class="column is-1">
    <button class="button is-danger" (click)="deleteElement()"> Del </button>
  </div>
</div>

// react_src/src/components/TodoItem.js
import React, { Component } from 'react'

class TodoItem extends Component {
  constructor (props) {
    super(props)

    this.state = {
      showInput: false
    }

    this.handleBlur = this.handleBlur.bind(this)
    this.handleClick = this.handleClick.bind(this)
    this.handleChange = this.handleChange.bind(this)
    this.handleItemClick = this.handleItemClick.bind(this)
  }

  handleItemClick () {
    this.setState({
      showInput: !this.state.showInput
    })
  }

  handleChange (event) {
    this.props.onChange({
      index: this.props.index,
      value: event.target.value
    })
  }

  handleBlur () {
    this.setState({
      showInput: !this.state.showInput
    })

    this.props.onChange({
      index: this.props.index,
      value: this.props.item
    })
  }

  handleClick () {
    this.props.onDelete(this.props.index)
  }

  render () {
    const showInput = this.state.showInput
    return (
      <div className="columns is-gapless">
        <div className="column is-11">
          {showInput ? (
            <input
              ref="input"
              className="input is-primary"
              type="text"
              value={this.props.item}
              onChange={this.handleChange}
              onBlur={this.handleBlur} />
          ) : (
            <li onClick={this.handleItemClick}> {this.props.item} </li>
          )}
        </div>

        <div className="column is-1">
          <button className="button is-danger" onClick={this.handleClick}> Del </button>
        </div>
      </div>
    )
  }
}

export default TodoItem
